---
- name: Update the ansible cache
  hosts: planet
  tags: ['cache']
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings

- include: components/opdk-apigee-mirror-create-download.yml
  vars:
    hosts: 'mirror'
  tags:
  - apigee-archive

- include: components/opdk-upload-apigee-mirror-archive.yml
  vars:
    hosts: 'planet'
  tags:
  - upload-archive
